/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperiencesRiversideRouteImport } from './routes/experiences/riverside'
import { Route as ExperiencesGrassfieldRouteImport } from './routes/experiences/grassfield'

const ExperiencesWaterFbmLazyRouteImport = createFileRoute(
  '/experiences/water-fbm',
)()
const ExperiencesGrassLazyRouteImport = createFileRoute('/experiences/grass')()
const ExperiencesBushLazyRouteImport = createFileRoute('/experiences/bush')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesWaterFbmLazyRoute = ExperiencesWaterFbmLazyRouteImport.update({
  id: '/experiences/water-fbm',
  path: '/experiences/water-fbm',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/experiences/water-fbm.lazy').then((d) => d.Route),
)
const ExperiencesGrassLazyRoute = ExperiencesGrassLazyRouteImport.update({
  id: '/experiences/grass',
  path: '/experiences/grass',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/experiences/grass.lazy').then((d) => d.Route),
)
const ExperiencesBushLazyRoute = ExperiencesBushLazyRouteImport.update({
  id: '/experiences/bush',
  path: '/experiences/bush',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/experiences/bush.lazy').then((d) => d.Route),
)
const ExperiencesRiversideRoute = ExperiencesRiversideRouteImport.update({
  id: '/experiences/riverside',
  path: '/experiences/riverside',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesGrassfieldRoute = ExperiencesGrassfieldRouteImport.update({
  id: '/experiences/grassfield',
  path: '/experiences/grassfield',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiences/grassfield': typeof ExperiencesGrassfieldRoute
  '/experiences/riverside': typeof ExperiencesRiversideRoute
  '/experiences/bush': typeof ExperiencesBushLazyRoute
  '/experiences/grass': typeof ExperiencesGrassLazyRoute
  '/experiences/water-fbm': typeof ExperiencesWaterFbmLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiences/grassfield': typeof ExperiencesGrassfieldRoute
  '/experiences/riverside': typeof ExperiencesRiversideRoute
  '/experiences/bush': typeof ExperiencesBushLazyRoute
  '/experiences/grass': typeof ExperiencesGrassLazyRoute
  '/experiences/water-fbm': typeof ExperiencesWaterFbmLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiences/grassfield': typeof ExperiencesGrassfieldRoute
  '/experiences/riverside': typeof ExperiencesRiversideRoute
  '/experiences/bush': typeof ExperiencesBushLazyRoute
  '/experiences/grass': typeof ExperiencesGrassLazyRoute
  '/experiences/water-fbm': typeof ExperiencesWaterFbmLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experiences/grassfield'
    | '/experiences/riverside'
    | '/experiences/bush'
    | '/experiences/grass'
    | '/experiences/water-fbm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/experiences/grassfield'
    | '/experiences/riverside'
    | '/experiences/bush'
    | '/experiences/grass'
    | '/experiences/water-fbm'
  id:
    | '__root__'
    | '/'
    | '/experiences/grassfield'
    | '/experiences/riverside'
    | '/experiences/bush'
    | '/experiences/grass'
    | '/experiences/water-fbm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperiencesGrassfieldRoute: typeof ExperiencesGrassfieldRoute
  ExperiencesRiversideRoute: typeof ExperiencesRiversideRoute
  ExperiencesBushLazyRoute: typeof ExperiencesBushLazyRoute
  ExperiencesGrassLazyRoute: typeof ExperiencesGrassLazyRoute
  ExperiencesWaterFbmLazyRoute: typeof ExperiencesWaterFbmLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/water-fbm': {
      id: '/experiences/water-fbm'
      path: '/experiences/water-fbm'
      fullPath: '/experiences/water-fbm'
      preLoaderRoute: typeof ExperiencesWaterFbmLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/grass': {
      id: '/experiences/grass'
      path: '/experiences/grass'
      fullPath: '/experiences/grass'
      preLoaderRoute: typeof ExperiencesGrassLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/bush': {
      id: '/experiences/bush'
      path: '/experiences/bush'
      fullPath: '/experiences/bush'
      preLoaderRoute: typeof ExperiencesBushLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/riverside': {
      id: '/experiences/riverside'
      path: '/experiences/riverside'
      fullPath: '/experiences/riverside'
      preLoaderRoute: typeof ExperiencesRiversideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/grassfield': {
      id: '/experiences/grassfield'
      path: '/experiences/grassfield'
      fullPath: '/experiences/grassfield'
      preLoaderRoute: typeof ExperiencesGrassfieldRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperiencesGrassfieldRoute: ExperiencesGrassfieldRoute,
  ExperiencesRiversideRoute: ExperiencesRiversideRoute,
  ExperiencesBushLazyRoute: ExperiencesBushLazyRoute,
  ExperiencesGrassLazyRoute: ExperiencesGrassLazyRoute,
  ExperiencesWaterFbmLazyRoute: ExperiencesWaterFbmLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
