/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\rafale.glb --transform -t 
Files: .\rafale.glb [28.79MB] > E:\Devs\Projects\portfolio-26\app\public\models\vehicles\rafale-transformed.glb [3.52MB] (88%)
*/

import * as THREE from "three";
import {
  MeshReflectorMaterial,
  PerspectiveCamera,
  RenderTexture,
  useGLTF,
} from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type { ThreeElements, ThreeEvent } from "@react-three/fiber";
import { Container, Fullscreen } from "@react-three/uikit";
import { useEffect, useRef, type FC } from "react";

type GLTFResult = GLTF & {
  nodes: {
    cockpit_left_screen: THREE.Mesh;
    cockpit_left_screen_bottom: THREE.Mesh;
    cockpit_left_screen_top: THREE.Mesh;
    cockpit_main_screen: THREE.Mesh;
    cockpit_right_screen: THREE.Mesh;
    cockpit_right_screen_bottom: THREE.Mesh;
    cockpit_right_screen_top: THREE.Mesh;
    cockpit_mirrors: THREE.Mesh;
    landing_gear_lights: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_2: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_49: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_50: THREE.Mesh;
    Object_51: THREE.Mesh;
    Object_52: THREE.Mesh;
    Object_53: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_55: THREE.Mesh;
    Object_56: THREE.Mesh;
    Object_57: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_59: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_60: THREE.Mesh;
    Object_61: THREE.Mesh;
    Object_62: THREE.Mesh;
    Object_63: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
  };
  materials: {
    Rafale_Set_4: THREE.MeshStandardMaterial;
    Glass: THREE.MeshStandardMaterial;
    Rafale_Fuel_Tank: THREE.MeshPhysicalMaterial;
    Rafale_Mica_IR: THREE.MeshStandardMaterial;
    Rafale_SBU_64: THREE.MeshStandardMaterial;
    Rafale_Set_1_2: THREE.MeshStandardMaterial;
    Rafale_Set_1_1: THREE.MeshStandardMaterial;
    Rafale_Set_2_1: THREE.MeshStandardMaterial;
    Rafale_Set_3: THREE.MeshStandardMaterial;
    Rafale_Set_2_2: THREE.MeshStandardMaterial;
    Rafale_Set_5: THREE.MeshStandardMaterial;
    Rafale_Set_6: THREE.MeshStandardMaterial;
    Mirrors: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

type LongFocusOptions = {
  // A position offset to apply to the camera position when focusing on the target.
  offset?: THREE.Vector3;

  // An optional fov to apply when focusing on the target.
  fov?: number;
};

type RafaleProps = ThreeElements["group"] & {
  onFocus?: (e: ThreeEvent<PointerEvent>) => void;
  onFocusEnd?: (e: ThreeEvent<PointerEvent>) => void;
  onLongFocus?: (lookAt: THREE.Vector3, options?: LongFocusOptions) => void;
  onLongFocusEnd?: () => void;
};

const Rafale: FC<RafaleProps> = ({ children, ...props }) => {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/rafale-transformed.glb",
  ) as unknown as GLTFResult;

  // Ref to store the timeout for long focus
  const focusTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const focusEndTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Cleanup the timeout on unmount
  useEffect(
    () => () => {
      if (focusTimeoutRef.current) {
        clearTimeout(focusTimeoutRef.current);
        focusTimeoutRef.current = null;
      }

      if (focusEndTimeoutRef.current) {
        clearTimeout(focusEndTimeoutRef.current);
        focusEndTimeoutRef.current = null;
      }
    },
    [],
  );

  const onPointerEnter = (
    e: ThreeEvent<PointerEvent>,
    options?: LongFocusOptions,
  ) => {
    // Prevent the event from propagating to other meshes
    e.stopPropagation();

    // Call the optional onFocus prop
    props.onFocus?.(e);

    // Stop the focus end timeout if it exists
    if (focusEndTimeoutRef.current) {
      clearTimeout(focusEndTimeoutRef.current);
      focusEndTimeoutRef.current = null;
    }

    // Start the timeout for long focus
    focusTimeoutRef.current = setTimeout(() => {
      const mesh = e.object as THREE.Mesh;

      // Compute the bounding box of the mesh to get its center position
      const bbox = new THREE.Box3().setFromObject(mesh);

      // Get the center of the bounding box
      const center = new THREE.Vector3();
      bbox.getCenter(center);

      props.onLongFocus?.(center, options);
    }, 1500);
  };

  const onPointerLeave = (e: ThreeEvent<PointerEvent>) => {
    if (!focusTimeoutRef.current) return;

    // Prevent the event from propagating to other meshes
    e.stopPropagation();

    // Call the optional onFocusEnd prop
    props.onFocusEnd?.(e);

    // Clear the timeout for long focus
    clearTimeout(focusTimeoutRef.current);
    focusTimeoutRef.current = null;

    // Wait a bit before calling it
    focusEndTimeoutRef.current = setTimeout(() => {
      props.onLongFocusEnd?.();
    }, 500);
  };

  return (
    <group {...props} dispose={null}>
      {
        // Attach the children to the group
        children
      }

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cockpit_left_screen.geometry}
        material={materials.Rafale_Set_4}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        onPointerEnter={(e) =>
          onPointerEnter(e, { offset: new THREE.Vector3(0, 0, 0.75) })
        }
        onPointerLeave={onPointerLeave}
      >
        <meshStandardMaterial>
          <RenderTexture attach="map" width={512} height={512}>
            <PerspectiveCamera makeDefault position={[0, 0, 5]} fov={75} />

            <Fullscreen flexDirection="row">
              <Container flexGrow={1} backgroundColor="red" />
              <Container flexGrow={1} backgroundColor="green" />
            </Fullscreen>
          </RenderTexture>
        </meshStandardMaterial>
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cockpit_main_screen.geometry}
        material={materials.Rafale_Set_4}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        onPointerEnter={(e) =>
          onPointerEnter(e, { offset: new THREE.Vector3(0, 0, 0) })
        }
        onPointerLeave={onPointerLeave}
      >
        <meshStandardMaterial>
          <RenderTexture attach="map" width={512} height={512}>
            <PerspectiveCamera makeDefault position={[0, 0, 5]} fov={75} />

            <Fullscreen flexDirection="row">
              <Container flexGrow={1} backgroundColor="red" />
              <Container flexGrow={1} backgroundColor="green" />
            </Fullscreen>
          </RenderTexture>
        </meshStandardMaterial>
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cockpit_right_screen.geometry}
        material={materials.Rafale_Set_4}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        onPointerEnter={(e) =>
          onPointerEnter(e, { offset: new THREE.Vector3(0, 0, -0.75) })
        }
        onPointerLeave={onPointerLeave}
      >
        <meshStandardMaterial>
          <RenderTexture attach="map" width={512} height={512}>
            <PerspectiveCamera makeDefault position={[0, 0, 5]} fov={75} />

            <Fullscreen flexDirection="row">
              <Container flexGrow={1} backgroundColor="red" />
              <Container flexGrow={1} backgroundColor="green" />
            </Fullscreen>
          </RenderTexture>
        </meshStandardMaterial>
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cockpit_left_screen_bottom.geometry}
        material={nodes.cockpit_left_screen_bottom.material}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        onPointerEnter={(e) =>
          onPointerEnter(e, { offset: new THREE.Vector3(0, 0, 0.75), fov: 45 })
        }
        onPointerLeave={onPointerLeave}
      >
        <meshStandardMaterial>
          <RenderTexture attach="map" width={512} height={512}>
            <PerspectiveCamera makeDefault position={[0, 0, 5]} fov={75} />

            <Fullscreen flexDirection="row">
              <Container flexGrow={1} backgroundColor="red" />
              <Container flexGrow={1} backgroundColor="green" />
            </Fullscreen>
          </RenderTexture>
        </meshStandardMaterial>
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cockpit_left_screen_top.geometry}
        material={nodes.cockpit_left_screen_top.material}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        onPointerEnter={(e) =>
          onPointerEnter(e, { offset: new THREE.Vector3(0, 0, 0.75), fov: 45 })
        }
        onPointerLeave={onPointerLeave}
      >
        <meshStandardMaterial>
          <RenderTexture attach="map" width={512} height={512}>
            <PerspectiveCamera makeDefault position={[0, 0, 5]} fov={75} />

            <Fullscreen flexDirection="row">
              <Container flexGrow={1} backgroundColor="red" />
              <Container flexGrow={1} backgroundColor="green" />
            </Fullscreen>
          </RenderTexture>
        </meshStandardMaterial>
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cockpit_right_screen_bottom.geometry}
        material={nodes.cockpit_right_screen_bottom.material}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        onPointerEnter={(e) =>
          onPointerEnter(e, { offset: new THREE.Vector3(0, 0, -0.75), fov: 45 })
        }
        onPointerLeave={onPointerLeave}
      >
        <meshStandardMaterial>
          <RenderTexture attach="map" width={512} height={512}>
            <PerspectiveCamera makeDefault position={[0, 0, 5]} fov={75} />

            <Fullscreen flexDirection="row">
              <Container flexGrow={1} backgroundColor="red" />
              <Container flexGrow={1} backgroundColor="green" />
            </Fullscreen>
          </RenderTexture>
        </meshStandardMaterial>
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cockpit_right_screen_top.geometry}
        material={nodes.cockpit_right_screen_top.material}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        onPointerEnter={(e) =>
          onPointerEnter(e, { offset: new THREE.Vector3(0, 0, -0.75), fov: 45 })
        }
        onPointerLeave={onPointerLeave}
      >
        <meshStandardMaterial>
          <RenderTexture attach="map" width={512} height={512}>
            <PerspectiveCamera makeDefault position={[0, 0, 5]} fov={75} />

            <Fullscreen flexDirection="row">
              <Container flexGrow={1} backgroundColor="red" />
              <Container flexGrow={1} backgroundColor="green" />
            </Fullscreen>
          </RenderTexture>
        </meshStandardMaterial>
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cockpit_mirrors.geometry}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <MeshReflectorMaterial resolution={256} color="#e3e3e3" metalness={1} />
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.landing_gear_lights.geometry}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial
          attach="material"
          emissive="#ffffff"
          emissiveIntensity={5}
          toneMapped={false}
        />
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Rafale_Fuel_Tank}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.Rafale_Mica_IR}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.Rafale_Mica_IR}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials.Rafale_SBU_64}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.Rafale_SBU_64}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.Rafale_SBU_64}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.Rafale_SBU_64}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.Rafale_SBU_64}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.Rafale_SBU_64}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.Rafale_SBU_64}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Rafale_Set_1_2}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.Rafale_SBU_64}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.Rafale_Set_1_1}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.Rafale_Set_1_1}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials.Rafale_Set_1_1}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.Rafale_Set_2_1}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_25.geometry}
        material={materials.Rafale_Set_2_1}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.Rafale_Set_2_1}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_27.geometry}
        material={materials.Rafale_Set_2_1}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials.Rafale_Set_2_1}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_29.geometry}
        material={materials.Rafale_Set_2_1}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.Rafale_Set_2_2}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_31.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_33.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_35.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_37.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_39.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Rafale_Set_5}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_41.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_43.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_45.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_47.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_49.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.Rafale_Set_5}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_51.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_52.geometry}
        material={materials.Rafale_Set_3}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_53.geometry}
        material={materials.Rafale_Set_4}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        material={materials.Rafale_Set_4}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_55.geometry}
        material={materials.Rafale_Set_4}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_56.geometry}
        material={materials.Rafale_Set_4}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_57.geometry}
        material={materials.Rafale_Set_4}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_58.geometry}
        material={materials.Rafale_Set_4}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_59.geometry}
        material={materials.Rafale_Set_4}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <meshPhysicalMaterial
          attach="material"
          color="#ffffff"
          roughness={0}
          metalness={0}
          ior={2.33}
          transmission={1}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials.Rafale_Set_6}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_61.geometry}
        material={materials.Rafale_Set_6}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials.Rafale_Set_6}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_63.geometry}
        material={materials.Rafale_Set_6}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Rafale_Fuel_Tank}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.Rafale_Fuel_Tank}
        position={[0, 26.289, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

export default Rafale;

useGLTF.preload("/models/vehicles/rafale-transformed.glb");
